/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmi_calculator;

/**
 *
 * @author Deborah
 */
public class BMI_CalculatorGUI extends javax.swing.JPanel {

    /**
     * Creates new form BMI_CalculatorGUI
     */
    public BMI_CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        genderSelectorGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        heightFeetInput = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        weightInput = new javax.swing.JTextField();
        heightLabel1 = new javax.swing.JLabel();
        heightLabel2 = new javax.swing.JLabel();
        heightInchesInput = new javax.swing.JTextField();
        heightLabel3 = new javax.swing.JLabel();
        heightLabel4 = new javax.swing.JLabel();
        heightLabel5 = new javax.swing.JLabel();
        ageInput = new javax.swing.JTextField();
        heightLabel6 = new javax.swing.JLabel();
        genderFemale = new javax.swing.JRadioButton();
        genderMale = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        outputPanel = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setText("Submit");

        titleLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        titleLabel1.setText("BMI Calculator");

        heightFeetInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        heightLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel.setLabelFor(weightInput);
        heightLabel.setText("Weight:");

        weightInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        heightLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel1.setLabelFor(heightFeetInput);
        heightLabel1.setText("Height: ");

        heightLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel2.setLabelFor(heightFeetInput);
        heightLabel2.setText("ft");

        heightInchesInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        heightLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel3.setLabelFor(heightInchesInput);
        heightLabel3.setText("in");

        heightLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel4.setLabelFor(weightInput);
        heightLabel4.setText("lbs");

        heightLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel5.setLabelFor(ageInput);
        heightLabel5.setText("Age:");

        ageInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        heightLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heightLabel6.setLabelFor(genderFemale);
        heightLabel6.setText("Gender: ");

        genderSelectorGroup.add(genderFemale);
        genderFemale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        genderFemale.setText("Female");
        genderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFemaleActionPerformed(evt);
            }
        });

        genderSelectorGroup.add(genderMale);
        genderMale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        genderMale.setText("Male");

        jLabel1.setText("* Required");

        jLabel2.setText("* Required");

        jLabel4.setText("* Required");

        jLabel5.setText("* Required");

        resultLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        resultLabel.setText("Your BMI is: ");

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addComponent(resultLabel)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addComponent(heightLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(ageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(heightLabel1))
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(heightFeetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(heightLabel2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(heightInchesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(heightLabel3))
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(heightLabel6)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel5)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(genderMale)
                                    .addGap(18, 18, 18)
                                    .addComponent(heightLabel))
                                .addComponent(genderFemale))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(weightInput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(heightLabel4))
                                .addComponent(jLabel4)))
                        .addComponent(jSeparator2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightFeetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel1)
                    .addComponent(heightLabel2)
                    .addComponent(heightInchesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel3)
                    .addComponent(heightLabel5)
                    .addComponent(ageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel6)
                    .addComponent(genderMale)
                    .addComponent(heightLabel)
                    .addComponent(weightInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(genderFemale))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(titleLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(titleLabel1)
                .addGap(18, 18, 18)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void genderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFemaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageInput;
    private javax.swing.JRadioButton genderFemale;
    private javax.swing.JRadioButton genderMale;
    private javax.swing.ButtonGroup genderSelectorGroup;
    private javax.swing.JTextField heightFeetInput;
    private javax.swing.JTextField heightInchesInput;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel heightLabel1;
    private javax.swing.JLabel heightLabel2;
    private javax.swing.JLabel heightLabel3;
    private javax.swing.JLabel heightLabel4;
    private javax.swing.JLabel heightLabel5;
    private javax.swing.JLabel heightLabel6;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField weightInput;
    // End of variables declaration//GEN-END:variables
}
